#!/bin/bash
BASEDIR=`dirname $0`
. $BASEDIR/io.sh 1 4 1 "$@"
CURDIR=`pwd`
set -xe

for ((i=1; i<=PNUM; i++)); do
    export PARAMS$i
done

for ((i=1; i<=ONUM; i++)); do
    export OUTPUTS$i
done

#The params1 must be the name of the configuration: topoflow_climate
transformation_file=${PARAMS1}
#The params2 must be the dataset_id. If we don't use localfiles, the problem is more simple
dataset_id=${PARAMS2}

#Create a directory with the templates
config_file_template=$(readlink -f /ws/templates/${transformation_file})
env_file=$(readlink -f /ws/.env.docker)
output=$(readlink -f $OUTPUTS1)

#This command replaces the variable in the template file
envsubst < ${config_file_template}.yaml > config.yml
config_file=${readlink -f config.yml}

pushd /ws
dotenv -f $env_file run python -m dtran.main exec_pipeline --config $config_file
#the output file is generated in the /ws directory, we must move to
mv $OUTPUTS1 $output 
popd


set -e
cd $BASEDIR
. $BASEDIR/output.sh
